image: python:3-alpine

before_script:
  - pip install pytest
  - apk update
  - apk add git mariadb-dev python3-dev yaml-dev postgresql-dev gcc musl-dev ca-certificates

stages:
  - build
  - test
  - deploy

job1:
  stage: build
  script:
    - "python setup.py install"
  only:
    - master

job2:
  stage: test
  script:
    - "pytest tests/"
  only:
    - master

