stages:
  - build
  - test
  - deploy

build_test:
  stage: test
  image: python:3-alpine
  before_script:
    - apk update
    - apk add git mariadb-dev python3-dev yaml-dev postgresql-dev gcc musl-dev ca-certificates
    - pip install pytest
    - python setup.py install
    - python setup.py sdist
  cache:
    key: sdist
    paths:
      - dist
  script:
    - "pytest tests/"
  only:
    - master

docker:
  stage: deploy
  image: docker:latest
  cache:
    key: sdist
    paths:
      - dist
    policy: pull
  before_script:
    - cp dist/*.tar.gz docker/
  script:
    - "docker build -t registry.dauehaus:5000/carbyne/logrdis:latest docker/"
    - "docker push registry.dauehaus:5000/carbyne/logrdis:latest"
  only:
    - master

