stages:
  - build
  - test
  - deploy

job1:
  image: python:3-alpine
  stage: test
  before_script:
    - apk update
    - apk add git mariadb-dev python3-dev yaml-dev postgresql-dev gcc musl-dev ca-certificates
    - pip install pytest
    - python setup.py install
  script:
    - "pytest tests/"
  only:
    - master

job2:
  stage: deploy
  image: docker:latest
  before_script:
    - apk update
    - apk add git mariadb-dev python3-dev yaml-dev postgresql-dev gcc musl-dev ca-certificates
    - python setup.py sdist
    - cp dist/*.tar.gz docker/
  script:
    - "docker build -t registry.dauehaus:5000/carbyne/logrdis:latest docker/"
    - "docker push registry.dauehaus:5000/carbyne/logrdis:latest"
  only:
    - master

