version: "3"

services:
  db:
    image: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_PASSWORD=default
      - POSTGRES_USER=squid
      - POSTGRES_DB=squidb

  squid:
    image: carbyne/squid
    links:
      - db
    depends_on:
      - db
    environment:
      - PGPASSWORD=default
    ports:
      - 3128:3128
      - 3129:3129
    volumes:
      - squiddata:/etc/squid:rw

  logrdis:
    image: carbyne/logrdis
    links:
      - squid
      - db
    depends_on:
      - squid
      - db
    volumes:
      - logrdisetc:/etc/logrdis:rw
      - logrdisdb:/var/lib/logrdis/logrdis.sql:rw
    environment:
      - DB_PROTO='postgresql'
      - DB_HOST='db'
      - DB_USER='squid'
      - DB_PASS='default'
      - DB_NAME='squidb'

volumes:
  dbdata:
  squiddata:
  logrdisetc:
  logrdisdb:
